#!/usr/bin/with-contenv bash

mkdir -p /config/{data,logs,run}


[[ -L /app/UniFi/data && ! /app/UniFi/data -ef /config/data ]] && unlink /app/UniFi/data
[[ -L /app/UniFi/logs && ! /app/UniFi/logs -ef /config/logs ]] && unlink /app/UniFi/logs
[[ -L /app/UniFi/run && ! /app/UniFi/run -ef /config/run ]] && unlink /app/UniFi/run


[[ ! -L /app/UniFi/data ]] && ln -s /config/data /app/UniFi/data
[[ ! -L /app/UniFi/logs ]] && ln -s /config/logs /app/UniFi/logs
[[ ! -L /app/UniFi/run ]] && ln -s /config/run /app/UniFi/run